# Generated by Django 4.2 on 2023-04-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_remove_question_lesson_question_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='questions',
        ),
        migrations.AddField(
            model_name='choice',
            name='questions',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.question'),
            preserve_default=False,
        ),
    ]
