# Generated by Django 4.2 on 2023-04-30 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_remove_choice_questions_choice_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
